# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projects\qgmailer\views\ui_main_view.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 675)
        MainWindow.setStyleSheet("#centralwidget { background: \"white\"; }\n"
"#sideBar{background-color: \"#404040\";}\n"
"\n"
"QTabBar::tab { height: 40px; width: 150px; }\n"
"QTabBar::tab::label{ font-size: 14px; font-weight: bold; }\n"
"QTabBar::tab:top { color: \"#eff0f1\"; border: 1px solid \"#76797C\"; background-color: \"#31363b\"; border-bottom: 1px transparent \"black\"; border-top-left-radius: 5px; border-top-right-radius: 5px; }\n"
"QTabBar::tab:top:hover { color: \"#eff0f1\"; border: 1px solid \"#76797C\"; background-color: \"#666666\"; border-bottom: 1px transparent \"black\"; border-top-left-radius: 5px; border-top-right-radius: 5px; }\n"
"QTabBar::tab:top:selected{ background-color: \"#23262a\";}\n"
"\n"
"\n"
"#personalPreviousBtn, #socialPreviousBtn, #promotionsPreviousBtn, #updatesPreviousBtn, #sentPreviousBtn, #trashPreviousBtn {background: transparent; border: none;}\n"
"#personalPreviousBtn:hover, #socialPreviousBtn:hover, #promotionsPreviousBtn:hover, #updatesPreviousBtn:hover, #sentPreviousBtn:hover, #trashPreviousBtn:hover {background: \"#d9d9d9\";}\n"
"\n"
"#personalNextBtn, #socialNextBtn, #promotionsNextBtn, #updatesNextBtn, #sentNextBtn, #trashNextBtn {background: transparent; border: none;}\n"
"#personalNextBtn:hover, #socialNextBtn:hover,  #promotionsNextBtn:hover, #updatesNextBtn:hover, #sentNextBtn:hover, #trashNextBtn:hover {background: \"#d9d9d9\"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sideBar = QtWidgets.QWidget(self.centralwidget)
        self.sideBar.setGeometry(QtCore.QRect(0, 1, 61, 673))
        self.sideBar.setObjectName("sideBar")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.sideBar)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, -5, 77, 679))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.sideBarInbox = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sideBarInbox.setMinimumSize(QtCore.QSize(60, 60))
        self.sideBarInbox.setMaximumSize(QtCore.QSize(60, 60))
        self.sideBarInbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sideBarInbox.setStyleSheet("#sideBarInbox {background: transparent; border: none;}\n"
"#sideBarInbox:hover {background: \"#666666\";}")
        self.sideBarInbox.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/inbox_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sideBarInbox.setIcon(icon)
        self.sideBarInbox.setIconSize(QtCore.QSize(50, 50))
        self.sideBarInbox.setObjectName("sideBarInbox")
        self.verticalLayout_4.addWidget(self.sideBarInbox)
        self.sideBarSend = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sideBarSend.setMinimumSize(QtCore.QSize(60, 60))
        self.sideBarSend.setMaximumSize(QtCore.QSize(60, 60))
        self.sideBarSend.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sideBarSend.setStyleSheet("#sideBarSend {background: transparent; border: none;}\n"
"#sideBarSend:hover {background: \"#666666\";}")
        self.sideBarSend.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/send_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sideBarSend.setIcon(icon1)
        self.sideBarSend.setIconSize(QtCore.QSize(50, 50))
        self.sideBarSend.setObjectName("sideBarSend")
        self.verticalLayout_4.addWidget(self.sideBarSend)
        self.sideBarContacts = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sideBarContacts.setMinimumSize(QtCore.QSize(60, 60))
        self.sideBarContacts.setMaximumSize(QtCore.QSize(60, 60))
        self.sideBarContacts.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sideBarContacts.setStyleSheet("#sideBarContacts {background: transparent; border: none;}\n"
"#sideBarContacts:hover {background: \"#666666\";}")
        self.sideBarContacts.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/contacts_icon2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sideBarContacts.setIcon(icon2)
        self.sideBarContacts.setIconSize(QtCore.QSize(50, 50))
        self.sideBarContacts.setObjectName("sideBarContacts")
        self.verticalLayout_4.addWidget(self.sideBarContacts)
        self.sideBarSent = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sideBarSent.setMinimumSize(QtCore.QSize(60, 60))
        self.sideBarSent.setMaximumSize(QtCore.QSize(60, 60))
        self.sideBarSent.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sideBarSent.setStyleSheet("#sideBarSent {background: transparent; border: none;}\n"
"#sideBarSent:hover {background: \"#666666\";}")
        self.sideBarSent.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/sent_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sideBarSent.setIcon(icon3)
        self.sideBarSent.setIconSize(QtCore.QSize(50, 50))
        self.sideBarSent.setObjectName("sideBarSent")
        self.verticalLayout_4.addWidget(self.sideBarSent)
        self.sideBarTrash = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sideBarTrash.setMinimumSize(QtCore.QSize(60, 60))
        self.sideBarTrash.setMaximumSize(QtCore.QSize(60, 60))
        self.sideBarTrash.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sideBarTrash.setStyleSheet("#sideBarTrash {background: transparent; border: none;}\n"
"#sideBarTrash:hover {background: \"#666666\";}")
        self.sideBarTrash.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/trash_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sideBarTrash.setIcon(icon4)
        self.sideBarTrash.setIconSize(QtCore.QSize(50, 50))
        self.sideBarTrash.setObjectName("sideBarTrash")
        self.verticalLayout_4.addWidget(self.sideBarTrash)
        self.sideBarSettings = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sideBarSettings.setMinimumSize(QtCore.QSize(60, 60))
        self.sideBarSettings.setMaximumSize(QtCore.QSize(60, 60))
        self.sideBarSettings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sideBarSettings.setStyleSheet("#sideBarSettings {background: transparent; border: none;}\n"
"#sideBarSettings:hover {background: \"#666666\";}")
        self.sideBarSettings.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/options_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sideBarSettings.setIcon(icon5)
        self.sideBarSettings.setIconSize(QtCore.QSize(50, 50))
        self.sideBarSettings.setObjectName("sideBarSettings")
        self.verticalLayout_4.addWidget(self.sideBarSettings)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(72, 60, 1027, 607))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.tabWidget = QtWidgets.QTabWidget(self.page)
        self.tabWidget.setGeometry(QtCore.QRect(24, 12, 985, 583))
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(5, 1, 5, 1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.personalIndexLabel = QtWidgets.QLabel(self.widget)
        self.personalIndexLabel.setObjectName("personalIndexLabel")
        self.horizontalLayout.addWidget(self.personalIndexLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.personalPreviousBtn = QtWidgets.QPushButton(self.widget)
        self.personalPreviousBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.personalPreviousBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.personalPreviousBtn.setStyleSheet("")
        self.personalPreviousBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/previous_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.personalPreviousBtn.setIcon(icon6)
        self.personalPreviousBtn.setIconSize(QtCore.QSize(20, 20))
        self.personalPreviousBtn.setObjectName("personalPreviousBtn")
        self.horizontalLayout.addWidget(self.personalPreviousBtn)
        self.personalNextBtn = QtWidgets.QPushButton(self.widget)
        self.personalNextBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.personalNextBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.personalNextBtn.setStyleSheet("")
        self.personalNextBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/next_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.personalNextBtn.setIcon(icon7)
        self.personalNextBtn.setIconSize(QtCore.QSize(20, 20))
        self.personalNextBtn.setObjectName("personalNextBtn")
        self.horizontalLayout.addWidget(self.personalNextBtn)
        self.verticalLayout.addWidget(self.widget)
        self.personalListView = QtWidgets.QListView(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.personalListView.sizePolicy().hasHeightForWidth())
        self.personalListView.setSizePolicy(sizePolicy)
        self.personalListView.setObjectName("personalListView")
        self.verticalLayout.addWidget(self.personalListView)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.tab_2)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(5, 1, 5, 1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.socialIndexLabel = QtWidgets.QLabel(self.widget_2)
        self.socialIndexLabel.setObjectName("socialIndexLabel")
        self.horizontalLayout_2.addWidget(self.socialIndexLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.socialPreviousBtn = QtWidgets.QPushButton(self.widget_2)
        self.socialPreviousBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.socialPreviousBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.socialPreviousBtn.setStyleSheet("")
        self.socialPreviousBtn.setText("")
        self.socialPreviousBtn.setIcon(icon6)
        self.socialPreviousBtn.setIconSize(QtCore.QSize(20, 20))
        self.socialPreviousBtn.setObjectName("socialPreviousBtn")
        self.horizontalLayout_2.addWidget(self.socialPreviousBtn)
        self.socialNextBtn = QtWidgets.QPushButton(self.widget_2)
        self.socialNextBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.socialNextBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.socialNextBtn.setStyleSheet("")
        self.socialNextBtn.setText("")
        self.socialNextBtn.setIcon(icon7)
        self.socialNextBtn.setIconSize(QtCore.QSize(20, 20))
        self.socialNextBtn.setObjectName("socialNextBtn")
        self.horizontalLayout_2.addWidget(self.socialNextBtn)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.socialListView = QtWidgets.QListView(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.socialListView.sizePolicy().hasHeightForWidth())
        self.socialListView.setSizePolicy(sizePolicy)
        self.socialListView.setObjectName("socialListView")
        self.verticalLayout_2.addWidget(self.socialListView)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.tab_3)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(5, 1, 5, 1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.promotionsIndexLabel = QtWidgets.QLabel(self.widget_3)
        self.promotionsIndexLabel.setObjectName("promotionsIndexLabel")
        self.horizontalLayout_3.addWidget(self.promotionsIndexLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.promotionsPreviousBtn = QtWidgets.QPushButton(self.widget_3)
        self.promotionsPreviousBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.promotionsPreviousBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.promotionsPreviousBtn.setStyleSheet("")
        self.promotionsPreviousBtn.setText("")
        self.promotionsPreviousBtn.setIcon(icon6)
        self.promotionsPreviousBtn.setIconSize(QtCore.QSize(20, 20))
        self.promotionsPreviousBtn.setObjectName("promotionsPreviousBtn")
        self.horizontalLayout_3.addWidget(self.promotionsPreviousBtn)
        self.promotionsNextBtn = QtWidgets.QPushButton(self.widget_3)
        self.promotionsNextBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.promotionsNextBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.promotionsNextBtn.setStyleSheet("")
        self.promotionsNextBtn.setText("")
        self.promotionsNextBtn.setIcon(icon7)
        self.promotionsNextBtn.setIconSize(QtCore.QSize(20, 20))
        self.promotionsNextBtn.setObjectName("promotionsNextBtn")
        self.horizontalLayout_3.addWidget(self.promotionsNextBtn)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.promotionsListView = QtWidgets.QListView(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.promotionsListView.sizePolicy().hasHeightForWidth())
        self.promotionsListView.setSizePolicy(sizePolicy)
        self.promotionsListView.setObjectName("promotionsListView")
        self.verticalLayout_3.addWidget(self.promotionsListView)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_4 = QtWidgets.QWidget(self.tab_4)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setContentsMargins(5, 1, 5, 1)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.updatesIndexLabel = QtWidgets.QLabel(self.widget_4)
        self.updatesIndexLabel.setObjectName("updatesIndexLabel")
        self.horizontalLayout_5.addWidget(self.updatesIndexLabel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.updatesPreviousBtn = QtWidgets.QPushButton(self.widget_4)
        self.updatesPreviousBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.updatesPreviousBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updatesPreviousBtn.setStyleSheet("")
        self.updatesPreviousBtn.setText("")
        self.updatesPreviousBtn.setIcon(icon6)
        self.updatesPreviousBtn.setIconSize(QtCore.QSize(20, 20))
        self.updatesPreviousBtn.setObjectName("updatesPreviousBtn")
        self.horizontalLayout_5.addWidget(self.updatesPreviousBtn)
        self.updatesNextBtn = QtWidgets.QPushButton(self.widget_4)
        self.updatesNextBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.updatesNextBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updatesNextBtn.setStyleSheet("")
        self.updatesNextBtn.setText("")
        self.updatesNextBtn.setIcon(icon7)
        self.updatesNextBtn.setIconSize(QtCore.QSize(20, 20))
        self.updatesNextBtn.setObjectName("updatesNextBtn")
        self.horizontalLayout_5.addWidget(self.updatesNextBtn)
        self.verticalLayout_6.addWidget(self.widget_4)
        self.updatesListView = QtWidgets.QListView(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.updatesListView.sizePolicy().hasHeightForWidth())
        self.updatesListView.setSizePolicy(sizePolicy)
        self.updatesListView.setObjectName("updatesListView")
        self.verticalLayout_6.addWidget(self.updatesListView)
        self.tabWidget.addTab(self.tab_4, "")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.toLineEdit = QtWidgets.QLineEdit(self.page_2)
        self.toLineEdit.setGeometry(QtCore.QRect(48, 36, 409, 37))
        self.toLineEdit.setStyleSheet("#toTextEdit {border: 1px solid \"#aaaaaa\";}")
        self.toLineEdit.setObjectName("toLineEdit")
        self.subjectLineEdit = QtWidgets.QLineEdit(self.page_2)
        self.subjectLineEdit.setGeometry(QtCore.QRect(48, 78, 409, 37))
        self.subjectLineEdit.setStyleSheet("#subjectTextEdit {border: 1px solid \"#aaaaaa\";}")
        self.subjectLineEdit.setObjectName("subjectLineEdit")
        self.messageTextEdit = QtWidgets.QTextEdit(self.page_2)
        self.messageTextEdit.setGeometry(QtCore.QRect(48, 120, 949, 397))
        self.messageTextEdit.setStyleSheet("#messageTextEdit {border: 1px solid \"#aaaaaa\";}")
        self.messageTextEdit.setObjectName("messageTextEdit")
        self.chooseContactsBtn = QtWidgets.QPushButton(self.page_2)
        self.chooseContactsBtn.setGeometry(QtCore.QRect(462, 36, 30, 30))
        self.chooseContactsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chooseContactsBtn.setStyleSheet("#chooseContactsBtn {background: transparent; border: none;}\n"
"#chooseContactsBtn:hover {background: \"#b3b3b3\"; border-radius: 15px;}")
        self.chooseContactsBtn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/choose_contact_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chooseContactsBtn.setIcon(icon8)
        self.chooseContactsBtn.setIconSize(QtCore.QSize(32, 32))
        self.chooseContactsBtn.setObjectName("chooseContactsBtn")
        self.sendMessageBtn = QtWidgets.QPushButton(self.page_2)
        self.sendMessageBtn.setGeometry(QtCore.QRect(48, 534, 67, 37))
        self.sendMessageBtn.setStyleSheet("#sendMessageBtn {background: \"#d9d9d9\"; border: none; border-radius: 5px;}\n"
"#sendMessageBtn:hover {background: \"#cccccc\";}\n"
"#sendMessageBtn:pressed {background: \"#b3b3b3\"; border-radius: 10px;}")
        self.sendMessageBtn.setObjectName("sendMessageBtn")
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.contactsListWidget = QtWidgets.QListWidget(self.page_4)
        self.contactsListWidget.setGeometry(QtCore.QRect(24, 12, 979, 481))
        self.contactsListWidget.setObjectName("contactsListWidget")
        self.contactsForm = QtWidgets.QWidget(self.page_4)
        self.contactsForm.setGeometry(QtCore.QRect(324, 120, 385, 217))
        self.contactsForm.setStyleSheet("background-color: \"white\";")
        self.contactsForm.setObjectName("contactsForm")
        self.contactsFormName = QtWidgets.QLineEdit(self.contactsForm)
        self.contactsFormName.setGeometry(QtCore.QRect(18, 48, 355, 25))
        self.contactsFormName.setObjectName("contactsFormName")
        self.contactsFormEmail = QtWidgets.QLineEdit(self.contactsForm)
        self.contactsFormEmail.setGeometry(QtCore.QRect(18, 120, 355, 25))
        self.contactsFormEmail.setObjectName("contactsFormEmail")
        self.nameIcon = QtWidgets.QLabel(self.contactsForm)
        self.nameIcon.setGeometry(QtCore.QRect(18, 18, 25, 25))
        self.nameIcon.setText("")
        self.nameIcon.setPixmap(QtGui.QPixmap(":/images/name_icon.png"))
        self.nameIcon.setScaledContents(True)
        self.nameIcon.setObjectName("nameIcon")
        self.emailIcon = QtWidgets.QLabel(self.contactsForm)
        self.emailIcon.setGeometry(QtCore.QRect(18, 90, 25, 25))
        self.emailIcon.setText("")
        self.emailIcon.setPixmap(QtGui.QPixmap(":/images/email_icon.png"))
        self.emailIcon.setScaledContents(True)
        self.emailIcon.setObjectName("emailIcon")
        self.contactsFormOk = QtWidgets.QPushButton(self.contactsForm)
        self.contactsFormOk.setGeometry(QtCore.QRect(18, 168, 55, 31))
        self.contactsFormOk.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.contactsFormOk.setFocusPolicy(QtCore.Qt.NoFocus)
        self.contactsFormOk.setStyleSheet("#contactsFormOk {background: \"#d9d9d9\"; border: none; border-radius: 5px;}\n"
"#contactsFormOk:hover {background: \"#cccccc\";}\n"
"#contactsFormOk:pressed {background: \"#b3b3b3\"; border-radius: 10px;}")
        self.contactsFormOk.setObjectName("contactsFormOk")
        self.contactsAdd = QtWidgets.QPushButton(self.page_4)
        self.contactsAdd.setGeometry(QtCore.QRect(24, 510, 55, 31))
        self.contactsAdd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.contactsAdd.setFocusPolicy(QtCore.Qt.NoFocus)
        self.contactsAdd.setStyleSheet("#contactsAdd {background: \"#d9d9d9\"; border: none; border-radius: 5px;}\n"
"#contactsAdd:hover {background: \"#cccccc\";}\n"
"#contactsAdd:pressed {background: \"#b3b3b3\"; border-radius: 10px;}")
        self.contactsAdd.setObjectName("contactsAdd")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.page_5)
        self.tabWidget_2.setGeometry(QtCore.QRect(24, 12, 985, 583))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_5 = QtWidgets.QWidget(self.tab_5)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setContentsMargins(5, 1, 5, 1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sentIndexLabel = QtWidgets.QLabel(self.widget_5)
        self.sentIndexLabel.setObjectName("sentIndexLabel")
        self.horizontalLayout_4.addWidget(self.sentIndexLabel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.sentPreviousBtn = QtWidgets.QPushButton(self.widget_5)
        self.sentPreviousBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.sentPreviousBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sentPreviousBtn.setStyleSheet("")
        self.sentPreviousBtn.setText("")
        self.sentPreviousBtn.setIcon(icon6)
        self.sentPreviousBtn.setIconSize(QtCore.QSize(20, 20))
        self.sentPreviousBtn.setObjectName("sentPreviousBtn")
        self.horizontalLayout_4.addWidget(self.sentPreviousBtn)
        self.sentNextBtn = QtWidgets.QPushButton(self.widget_5)
        self.sentNextBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.sentNextBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sentNextBtn.setStyleSheet("")
        self.sentNextBtn.setText("")
        self.sentNextBtn.setIcon(icon7)
        self.sentNextBtn.setIconSize(QtCore.QSize(20, 20))
        self.sentNextBtn.setObjectName("sentNextBtn")
        self.horizontalLayout_4.addWidget(self.sentNextBtn)
        self.verticalLayout_5.addWidget(self.widget_5)
        self.sentListView = QtWidgets.QListView(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.sentListView.sizePolicy().hasHeightForWidth())
        self.sentListView.setSizePolicy(sizePolicy)
        self.sentListView.setObjectName("sentListView")
        self.verticalLayout_5.addWidget(self.sentListView)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.page_6)
        self.tabWidget_3.setGeometry(QtCore.QRect(24, 12, 985, 583))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_7 = QtWidgets.QWidget(self.tab_7)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_7.setContentsMargins(5, 1, 5, 1)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.trashIndexLabel = QtWidgets.QLabel(self.widget_7)
        self.trashIndexLabel.setObjectName("trashIndexLabel")
        self.horizontalLayout_7.addWidget(self.trashIndexLabel)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.trashPreviousBtn = QtWidgets.QPushButton(self.widget_7)
        self.trashPreviousBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.trashPreviousBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.trashPreviousBtn.setStyleSheet("")
        self.trashPreviousBtn.setText("")
        self.trashPreviousBtn.setIcon(icon6)
        self.trashPreviousBtn.setIconSize(QtCore.QSize(20, 20))
        self.trashPreviousBtn.setObjectName("trashPreviousBtn")
        self.horizontalLayout_7.addWidget(self.trashPreviousBtn)
        self.trashNextBtn = QtWidgets.QPushButton(self.widget_7)
        self.trashNextBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.trashNextBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.trashNextBtn.setStyleSheet("")
        self.trashNextBtn.setText("")
        self.trashNextBtn.setIcon(icon7)
        self.trashNextBtn.setIconSize(QtCore.QSize(20, 20))
        self.trashNextBtn.setObjectName("trashNextBtn")
        self.horizontalLayout_7.addWidget(self.trashNextBtn)
        self.verticalLayout_8.addWidget(self.widget_7)
        self.trashListView = QtWidgets.QListView(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.trashListView.sizePolicy().hasHeightForWidth())
        self.trashListView.setSizePolicy(sizePolicy)
        self.trashListView.setObjectName("trashListView")
        self.verticalLayout_8.addWidget(self.trashListView)
        self.tabWidget_3.addTab(self.tab_7, "")
        self.stackedWidget.addWidget(self.page_6)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.containerQWebEngine = QtWidgets.QWidget(self.page_3)
        self.containerQWebEngine.setGeometry(QtCore.QRect(12, 18, 1001, 571))
        self.containerQWebEngine.setObjectName("containerQWebEngine")
        self.layoutQWebEngine = QtWidgets.QHBoxLayout(self.containerQWebEngine)
        self.layoutQWebEngine.setContentsMargins(0, 0, 0, 0)
        self.layoutQWebEngine.setObjectName("layoutQWebEngine")
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.personalIndexLabel.setText(_translate("MainWindow", "0 - 0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Personal"))
        self.socialIndexLabel.setText(_translate("MainWindow", "0 - 0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Social"))
        self.promotionsIndexLabel.setText(_translate("MainWindow", "0 - 0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Promotions"))
        self.updatesIndexLabel.setText(_translate("MainWindow", "0 - 0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Updates"))
        self.toLineEdit.setPlaceholderText(_translate("MainWindow", "To"))
        self.subjectLineEdit.setPlaceholderText(_translate("MainWindow", "Subject"))
        self.sendMessageBtn.setText(_translate("MainWindow", "Send"))
        self.contactsFormName.setPlaceholderText(_translate("MainWindow", "Name"))
        self.contactsFormEmail.setPlaceholderText(_translate("MainWindow", "Email"))
        self.contactsFormOk.setText(_translate("MainWindow", "OK"))
        self.contactsAdd.setText(_translate("MainWindow", "Add"))
        self.sentIndexLabel.setText(_translate("MainWindow", "0 - 0"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Sent"))
        self.trashIndexLabel.setText(_translate("MainWindow", "0 - 0"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Trash"))

from views.icons import icons_rc
