# Label ids are for internal use only.
# This is mainly for efficiency, in order to avoid string allocations and comparisons.
LABEL_ID_PERSONAL = 1
LABEL_ID_UPDATES = 2
LABEL_ID_SOCIAL = 3
LABEL_ID_PROMOTIONS = 4
LABEL_ID_SENT = 5
LABEL_ID_TRASH = 6
###############
# These are ids of labels in Gmail-API. Internally called gmail-labels.
GMAIL_LABEL_PERSONAL = 'CATEGORY_PERSONAL'
GMAIL_LABEL_UPDATES = 'CATEGORY_UPDATES'
GMAIL_LABEL_SOCIAL = 'CATEGORY_SOCIAL'
GMAIL_LABEL_PROMOTIONS = 'CATEGORY_PROMOTIONS'
GMAIL_LABEL_SENT = 'SENT'
GMAIL_LABEL_TRASH = 'TRASH'
GMAIL_LABEL_UNREAD = 'UNREAD'
###############

LABEL_ID_TO_LABEL = {
    LABEL_ID_PERSONAL: GMAIL_LABEL_PERSONAL,
    LABEL_ID_UPDATES: GMAIL_LABEL_UPDATES,
    LABEL_ID_SOCIAL: GMAIL_LABEL_SOCIAL,
    LABEL_ID_PROMOTIONS: GMAIL_LABEL_PROMOTIONS,
    LABEL_ID_SENT: GMAIL_LABEL_SENT,
    LABEL_ID_TRASH: GMAIL_LABEL_TRASH,
}

LABEL_TO_LABEL_ID = {
    GMAIL_LABEL_PERSONAL: LABEL_ID_PERSONAL,
    GMAIL_LABEL_UPDATES: LABEL_ID_UPDATES,
    GMAIL_LABEL_SOCIAL: LABEL_ID_SOCIAL,
    GMAIL_LABEL_PROMOTIONS: LABEL_ID_PROMOTIONS,
    GMAIL_LABEL_SENT: LABEL_ID_SENT,
    GMAIL_LABEL_TRASH: LABEL_ID_TRASH,
    # Gmail api also defines forums label id, which I might add in future.
}
