LABEL_ID_PERSONAL = 1
LABEL_ID_UPDATES = 2
LABEL_ID_SOCIAL = 3
LABEL_ID_PROMOTIONS = 4
LABEL_ID_SENT = 5
LABEL_ID_TRASH = 6

LABEL_ID_TO_LABEL = {
    LABEL_ID_PERSONAL: 'CATEGORY_PERSONAL',
    LABEL_ID_UPDATES: 'CATEGORY_SOCIAL',
    LABEL_ID_PROMOTIONS: 'CATEGORY_PROMOTIONS',
    LABEL_ID_SENT: 'SENT',
    LABEL_ID_TRASH: 'TRASH',
}

LABEL_TO_LABEL_ID = {
    'CATEGORY_PERSONAL': LABEL_ID_PERSONAL,
    'CATEGORY_UPDATES': LABEL_ID_UPDATES,
    'CATEGORY_SOCIAL': LABEL_ID_SOCIAL,
    'CATEGORY_PROMOTIONS': LABEL_ID_PROMOTIONS,
    'SENT': LABEL_ID_SENT,
    'TRASH': LABEL_ID_TRASH,
    # Gmail api also defines forums label id, which I might add in future.
}
